#include <stdio.h>
#include <stdlib.h>
#include "ast.h"
static void codegen_error(const char *m){fprintf(stderr,"jcm: codegen: %s\n",m);}
static const char *runtime_symbol(enum JCMOp op){switch(op){case JCM_AND:return "jcm_runtime_and";case JCM_OR:return "jcm_runtime_or";case JCM_NOT:return "jcm_runtime_not";case JCM_EQ:return "jcm_runtime_eq";case JCM_LT:return "jcm_runtime_lt";case JCM_LE:return "jcm_runtime_le";case JCM_GT:return "jcm_runtime_gt";case JCM_GE:return "jcm_runtime_ge";case JCM_SUM:return "jcm_runtime_sum";case JCM_PRODUCT:return "jcm_runtime_product";case JCM_INTEGRAL:return "jcm_runtime_integral";case JCM_IF:return "jcm_runtime_if";case JCM_LAMBDA:return "jcm_runtime_lambda";case JCM_BIND:return "jcm_runtime_bind";case JCM_LOAD:return "jcm_runtime_load";case JCM_STORE:return "jcm_runtime_store";case JCM_INPUT:return "jcm_runtime_input";case JCM_OUTPUT:return "jcm_runtime_output";default:return "jcm_runtime_generic";}}
static int emit_number(FILE *o,long long n){fprintf(o,"    mov $%lld, %%rax\n",n);return 1;}
static int emit_runtime(FILE *o,enum JCMOp op){fprintf(o,"    call %s\n",runtime_symbol(op));return 1;}
static int emit_expression(FILE *o,const struct JCMAst *a){enum JCMOp op;const struct JCMAst *l,*q;if(!a)return 0;if(a->kind==JCM_AST_NUMBER)return emit_number(o,a->value.number);if(a->kind==JCM_AST_STRING){fprintf(o,"    xor %%eax, %%eax\n");return 1;}if(a->kind!=JCM_AST_LIST||!a->value.list.count)return 0;if(a->value.list.items[0]->kind!=JCM_AST_CORE){codegen_error("function calls require the runtime backend");return 0;}op=a->value.list.items[0]->value.op;if(op!=JCM_ADD&&op!=JCM_SUB&&op!=JCM_MUL&&op!=JCM_DIV&&op!=JCM_MOD)return emit_runtime(o,op);if(a->value.list.count!=3)return 0;l=a->value.list.items[1];q=a->value.list.items[2];if(!emit_expression(o,l))return 0;fprintf(o,"    push %%rax\n");if(!emit_expression(o,q))return 0;fprintf(o,"    mov %%rax, %%rbx\n    pop %%rax\n");if(op==JCM_ADD)fprintf(o,"    add %%rbx, %%rax\n");else if(op==JCM_SUB)fprintf(o,"    sub %%rbx, %%rax\n");else if(op==JCM_MUL)fprintf(o,"    imul %%rbx, %%rax\n");else {fprintf(o,"    cqo\n    idiv %%rbx\n");if(op==JCM_MOD)fprintf(o,"    mov %%rdx, %%rax\n");}return 1;}
int jcm_codegen(FILE *o,const struct JCMAst *p){int i;if(!o||!p||p->kind!=JCM_AST_PROGRAM){codegen_error("expected program AST");return 0;}fprintf(o,".text\n.globl main\n.type main, @function\n");fprintf(o,".extern jcm_runtime_sum\n.extern jcm_runtime_product\n.extern jcm_runtime_integral\n.extern jcm_runtime_generic\nmain:\n    push %%rbp\n    mov %%rsp, %%rbp\n");if(!p->value.list.count)fprintf(o,"    xor %%eax, %%eax\n");else for(i=0;i<p->value.list.count;i++)if(!emit_expression(o,p->value.list.items[i])){fprintf(o,"    mov $1, %%eax\n    leave\n    ret\n");return 0;}fprintf(o,"    leave\n    ret\n.size main, .-main\n");return 1;}
